#!/bin/sh

### BEGIN INIT INFO
# Provides:          xbmc-rfid-music
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: rfid playback trigger for XBMC
# Description:       Trigger playback in XBMC by swiping RFID cards
### END INIT INFO

# Configure these:
DIR=/home/rfid/xbmc-rfid-music
DAEMON_USER=rfid
# End of Config

DAEMON=$DIR/rfid-music.py
DAEMON_NAME=rfid-music
PIDFILE=$DIR/$DAEMON_NAME.pid

. /lib/lsb/init-functions
 
do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}
 
case "$1" in
 
    start|stop)
        do_${1}
        ;;
 
    restart|reload|force-reload)
        do_stop
        do_start
        ;;
 
    status)
        status_of_proc -p $PIDFILE "$WEB_DAEMON_NAME" "$WEB_DAEMON"
        ;;
    *)
        echo "Usage: /etc/init.d/xbmc-rfid-music {start|stop|restart|status}"
        exit 1
        ;;
 
esac
exit 0
